- name: Azure Static Web Apps Deploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    # Action to perform
    action: 
    # Directory location of the application source code
    app_location: 
    # Required token
    azure_static_web_apps_api_token: 
    # Custom command for Oryx to run when building Azure Functions source code
    api_build_command: # optional
    # Directory location of the Azure Functions source code
    api_location: # optional
    # Identical in use to output_location
    app_artifact_location: # optional
    # Directory location of the compiled application code after building
    output_location: # optional
    # Custom command for Oryx to run when building application source code
    app_build_command: # optional
    # Token for interacting with the Github repository. Currently used only for commenting on Pull Requests.
    repo_token: # optional
    # Directory location where the routes.json file can be found in the source code
    routes_location: # optional
    # Skips the build step for the application source code if set to true.
    skip_app_build: # optional
